plugins {
    id("org.jetbrains.kotlin.jvm").version("1.7.0")
    id("org.jetbrains.kotlin.kapt").version("1.7.21")
}

apply from: '../jitpack.gradle'

java {
    withSourcesJar()
    withJavadocJar()
}

publishing {
    publications {
        maven(MavenPublication) {
            from components.java
        }
    }
}


dependencies {
    api(project(":stone_lib"))
}


