[versions]

stone = "1.0.7"

kotlin = "1.7.0"
ksp = "2.1.10-1.0.30"

jetbrain-immutable = "0.3.7"
jetbrain-coroutines = "1.10.1"

kotlinpoet = "2.0.0"

jupiter = "5.9.2"


[libraries]

jetbrain-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "jetbrain-immutable" }
jetbrain-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "jetbrain-coroutines" }

ksp = { group = "com.google.devtools.ksp", name = "symbol-processing-api", version.ref = "ksp" }

kotlinpoet = { group = "com.squareup", name = "kotlinpoet", version.ref = "kotlinpoet" }
kotlinpoet-ksp = { group = "com.squareup", name = "kotlinpoet-ksp", version.ref = "kotlinpoet" }

# test
jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "jupiter" }
jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "jupiter" }

[bundles]

kotlin = ["jetbrain-coroutines", "jetbrain-immutable"]
kotlinpoet = ["kotlinpoet", "kotlinpoet-ksp"]

[plugins]

kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
android-libarary = { id = "com.android.library", version = "8.12.3" }

publish-maven = { id = "org.gradle.maven-publish" }
publish-stone = { id = "com.github.klee0kai.stone.publish" }
