[versions]

stone = "1.0.7"

kotlin = "2.2.21"
ksp = "2.1.10-1.0.30"
agp = "8.12.3"

appcompat = "1.7.1"
javax-inject = "1"
kotlinx-coroutines = "1.10.1"

auto-service = "1.1.1"
incap = "1.0.0"
javapoet = "1.13.0"

junit = "6.0.0"
junit-launcher = "6.0.0"
testing-compile = "0.23.0"


[libraries]

android-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }

# https://mvnrepository.com/artifact/javax.inject/javax.inject
java-inject = { group = "javax.inject", name = "javax.inject", version.ref = "javax-inject" }

kotlinx-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }

auto-service = { group = "com.google.auto.service", name = "auto-service", version.ref = "auto-service" }

incap = { group = "net.ltgt.gradle.incap", name = "incap", version.ref = "incap" }
incap-processor = { group = "net.ltgt.gradle.incap", name = "incap-processor", version.ref = "incap" }

javapoet = { group = "com.squareup", name = "javapoet", version.ref = "javapoet" }

ksp = { group = "com.google.devtools.ksp", name = "symbol-processing-api", version.ref = "ksp" }

jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }
jupiter-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junit-launcher" }

testing-compile = { group = "com.google.testing.compile", name = "compile-testing", version.ref = "testing-compile" }

[bundles]

junit = ["jupiter-api", "jupiter-engine", "jupiter-launcher"]

[plugins]

kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-dsl = { id = "org.gradle.kotlin.kotlin-dsl", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }

publish-maven = { id = "org.gradle.maven-publish" }
publish-stone = { id = "com.github.klee0kai.stone.publish" }
