package com.github.klee0kai.thekey.stone.ksp.poet

import com.github.klee0kai.thekey.stone.ksp.Processor
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.ParameterSpec
import com.squareup.kotlinpoet.PropertySpec

@DslMarker
annotation class PoetDsl

fun FileSpec.Builder.genLibComment() {
    addFileComment("Generated by Stone Library\n")
    addFileComment("Project " + Processor.PROJECT_URL + "\n")
    addFileComment("Copyright (c) 2022 Andrey Kuzubov")
}


fun PropertySpec.asParameter(): ParameterSpec = ParameterSpec.builder(name, type).build()

fun PropertySpec.Builder.initFromConstructor(): PropertySpec.Builder = apply { initializer(build().name) }

fun Collection<CodeBlock>.toCodeBlock(): CodeBlock {
    val blocks = this
    return CodeBlock.builder().apply {
        blocks.forEach {
            add(it)
        }
    }.build()
}
