name: Deploy Debug Jobs

on:
  workflow_dispatch:

jobs:
  hello_world:
    name: Simple Hello World
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - uses: klee0kai/screwdriver@master
        with:
          gh_api_token:  ${{ secrets.SECRETS_GH_API_TOKEN }}
          cmd: "hello_world -l -d --summary"